Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: dm-
    SupplierDeployMetadata:
      FileArtifactRelation:
        '{{ computenest::file::springboot }}':
          ArtifactId: artifact-4e82b449817b4947a234
    TemplateConfigs:
      - Name: 集群版
        Url: 'ros_templates/template.yaml'
        ArchitectureDiagramUrl: 'docs/architecture.png'
        AllowedRegions:
          - cn-beijing
          - cn-hangzhou
          - cn-shanghai
  ServiceType: private
  OperationMetadata:
    ModifyParametersConfig:
      - TemplateName: 集群版
        Operation:
          - Name: 变配ECS实例规格
            Description: 变配ECS实例规格
            Type: Custom
            SupportPredefinedParameters: false
            EnableLogging: false
            Parameters:
              - EcsInstanceType
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: spring boot demo
    Image: 'resources/icons/service_logo.png'
    Name: SpringBoot弹性集群版
  ShareType: Public
  ApprovalType: Manual